/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SSlugRouteImport } from './routes/s.$slug'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as ApiPublicMpWebhookRouteImport } from './routes/api/public/mp-webhook'
import { Route as AuthenticatedAppSettingsRouteImport } from './routes/_authenticated/app.settings'
import { Route as AuthenticatedAppReferralsRouteImport } from './routes/_authenticated/app.referrals'
import { Route as AuthenticatedAppNewRouteImport } from './routes/_authenticated/app.new'
import { Route as AuthenticatedAppLeadsRouteImport } from './routes/_authenticated/app.leads'
import { Route as AuthenticatedAppFollowupsRouteImport } from './routes/_authenticated/app.followups'
import { Route as AuthenticatedAppDocsRouteImport } from './routes/_authenticated/app.docs'
import { Route as AuthenticatedAppCrmRouteImport } from './routes/_authenticated/app.crm'
import { Route as AuthenticatedAppBuscarRouteImport } from './routes/_authenticated/app.buscar'
import { Route as AuthenticatedAppBillingRouteImport } from './routes/_authenticated/app.billing'
import { Route as AuthenticatedAppAgendaRouteImport } from './routes/_authenticated/app.agenda'
import { Route as AuthenticatedAppAdminRouteImport } from './routes/_authenticated/app.admin'
import { Route as AuthenticatedAppSitesIndexRouteImport } from './routes/_authenticated/app.sites.index'
import { Route as AuthenticatedAppSitesIdRouteImport } from './routes/_authenticated/app.sites.$id'
import { Route as AuthenticatedAppBillingSuccessRouteImport } from './routes/_authenticated/app.billing.success'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SSlugRoute = SSlugRouteImport.update({
  id: '/s/$slug',
  path: '/s/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicMpWebhookRoute = ApiPublicMpWebhookRouteImport.update({
  id: '/api/public/mp-webhook',
  path: '/api/public/mp-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppSettingsRoute =
  AuthenticatedAppSettingsRouteImport.update({
    id: '/app/settings',
    path: '/app/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppReferralsRoute =
  AuthenticatedAppReferralsRouteImport.update({
    id: '/app/referrals',
    path: '/app/referrals',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppNewRoute = AuthenticatedAppNewRouteImport.update({
  id: '/app/new',
  path: '/app/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppLeadsRoute = AuthenticatedAppLeadsRouteImport.update({
  id: '/app/leads',
  path: '/app/leads',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppFollowupsRoute =
  AuthenticatedAppFollowupsRouteImport.update({
    id: '/app/followups',
    path: '/app/followups',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppDocsRoute = AuthenticatedAppDocsRouteImport.update({
  id: '/app/docs',
  path: '/app/docs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppCrmRoute = AuthenticatedAppCrmRouteImport.update({
  id: '/app/crm',
  path: '/app/crm',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppBuscarRoute = AuthenticatedAppBuscarRouteImport.update({
  id: '/app/buscar',
  path: '/app/buscar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppBillingRoute = AuthenticatedAppBillingRouteImport.update({
  id: '/app/billing',
  path: '/app/billing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppAgendaRoute = AuthenticatedAppAgendaRouteImport.update({
  id: '/app/agenda',
  path: '/app/agenda',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppAdminRoute = AuthenticatedAppAdminRouteImport.update({
  id: '/app/admin',
  path: '/app/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppSitesIndexRoute =
  AuthenticatedAppSitesIndexRouteImport.update({
    id: '/app/sites/',
    path: '/app/sites/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppSitesIdRoute = AuthenticatedAppSitesIdRouteImport.update({
  id: '/app/sites/$id',
  path: '/app/sites/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppBillingSuccessRoute =
  AuthenticatedAppBillingSuccessRouteImport.update({
    id: '/success',
    path: '/success',
    getParentRoute: () => AuthenticatedAppBillingRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/s/$slug': typeof SSlugRoute
  '/app/admin': typeof AuthenticatedAppAdminRoute
  '/app/agenda': typeof AuthenticatedAppAgendaRoute
  '/app/billing': typeof AuthenticatedAppBillingRouteWithChildren
  '/app/buscar': typeof AuthenticatedAppBuscarRoute
  '/app/crm': typeof AuthenticatedAppCrmRoute
  '/app/docs': typeof AuthenticatedAppDocsRoute
  '/app/followups': typeof AuthenticatedAppFollowupsRoute
  '/app/leads': typeof AuthenticatedAppLeadsRoute
  '/app/new': typeof AuthenticatedAppNewRoute
  '/app/referrals': typeof AuthenticatedAppReferralsRoute
  '/app/settings': typeof AuthenticatedAppSettingsRoute
  '/api/public/mp-webhook': typeof ApiPublicMpWebhookRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/billing/success': typeof AuthenticatedAppBillingSuccessRoute
  '/app/sites/$id': typeof AuthenticatedAppSitesIdRoute
  '/app/sites/': typeof AuthenticatedAppSitesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/s/$slug': typeof SSlugRoute
  '/app/admin': typeof AuthenticatedAppAdminRoute
  '/app/agenda': typeof AuthenticatedAppAgendaRoute
  '/app/billing': typeof AuthenticatedAppBillingRouteWithChildren
  '/app/buscar': typeof AuthenticatedAppBuscarRoute
  '/app/crm': typeof AuthenticatedAppCrmRoute
  '/app/docs': typeof AuthenticatedAppDocsRoute
  '/app/followups': typeof AuthenticatedAppFollowupsRoute
  '/app/leads': typeof AuthenticatedAppLeadsRoute
  '/app/new': typeof AuthenticatedAppNewRoute
  '/app/referrals': typeof AuthenticatedAppReferralsRoute
  '/app/settings': typeof AuthenticatedAppSettingsRoute
  '/api/public/mp-webhook': typeof ApiPublicMpWebhookRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/billing/success': typeof AuthenticatedAppBillingSuccessRoute
  '/app/sites/$id': typeof AuthenticatedAppSitesIdRoute
  '/app/sites': typeof AuthenticatedAppSitesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/s/$slug': typeof SSlugRoute
  '/_authenticated/app/admin': typeof AuthenticatedAppAdminRoute
  '/_authenticated/app/agenda': typeof AuthenticatedAppAgendaRoute
  '/_authenticated/app/billing': typeof AuthenticatedAppBillingRouteWithChildren
  '/_authenticated/app/buscar': typeof AuthenticatedAppBuscarRoute
  '/_authenticated/app/crm': typeof AuthenticatedAppCrmRoute
  '/_authenticated/app/docs': typeof AuthenticatedAppDocsRoute
  '/_authenticated/app/followups': typeof AuthenticatedAppFollowupsRoute
  '/_authenticated/app/leads': typeof AuthenticatedAppLeadsRoute
  '/_authenticated/app/new': typeof AuthenticatedAppNewRoute
  '/_authenticated/app/referrals': typeof AuthenticatedAppReferralsRoute
  '/_authenticated/app/settings': typeof AuthenticatedAppSettingsRoute
  '/api/public/mp-webhook': typeof ApiPublicMpWebhookRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/billing/success': typeof AuthenticatedAppBillingSuccessRoute
  '/_authenticated/app/sites/$id': typeof AuthenticatedAppSitesIdRoute
  '/_authenticated/app/sites/': typeof AuthenticatedAppSitesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/s/$slug'
    | '/app/admin'
    | '/app/agenda'
    | '/app/billing'
    | '/app/buscar'
    | '/app/crm'
    | '/app/docs'
    | '/app/followups'
    | '/app/leads'
    | '/app/new'
    | '/app/referrals'
    | '/app/settings'
    | '/api/public/mp-webhook'
    | '/app/'
    | '/app/billing/success'
    | '/app/sites/$id'
    | '/app/sites/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/s/$slug'
    | '/app/admin'
    | '/app/agenda'
    | '/app/billing'
    | '/app/buscar'
    | '/app/crm'
    | '/app/docs'
    | '/app/followups'
    | '/app/leads'
    | '/app/new'
    | '/app/referrals'
    | '/app/settings'
    | '/api/public/mp-webhook'
    | '/app'
    | '/app/billing/success'
    | '/app/sites/$id'
    | '/app/sites'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/s/$slug'
    | '/_authenticated/app/admin'
    | '/_authenticated/app/agenda'
    | '/_authenticated/app/billing'
    | '/_authenticated/app/buscar'
    | '/_authenticated/app/crm'
    | '/_authenticated/app/docs'
    | '/_authenticated/app/followups'
    | '/_authenticated/app/leads'
    | '/_authenticated/app/new'
    | '/_authenticated/app/referrals'
    | '/_authenticated/app/settings'
    | '/api/public/mp-webhook'
    | '/_authenticated/app/'
    | '/_authenticated/app/billing/success'
    | '/_authenticated/app/sites/$id'
    | '/_authenticated/app/sites/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  SSlugRoute: typeof SSlugRoute
  ApiPublicMpWebhookRoute: typeof ApiPublicMpWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$slug': {
      id: '/s/$slug'
      path: '/s/$slug'
      fullPath: '/s/$slug'
      preLoaderRoute: typeof SSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/mp-webhook': {
      id: '/api/public/mp-webhook'
      path: '/api/public/mp-webhook'
      fullPath: '/api/public/mp-webhook'
      preLoaderRoute: typeof ApiPublicMpWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/settings': {
      id: '/_authenticated/app/settings'
      path: '/app/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AuthenticatedAppSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/referrals': {
      id: '/_authenticated/app/referrals'
      path: '/app/referrals'
      fullPath: '/app/referrals'
      preLoaderRoute: typeof AuthenticatedAppReferralsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/new': {
      id: '/_authenticated/app/new'
      path: '/app/new'
      fullPath: '/app/new'
      preLoaderRoute: typeof AuthenticatedAppNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/leads': {
      id: '/_authenticated/app/leads'
      path: '/app/leads'
      fullPath: '/app/leads'
      preLoaderRoute: typeof AuthenticatedAppLeadsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/followups': {
      id: '/_authenticated/app/followups'
      path: '/app/followups'
      fullPath: '/app/followups'
      preLoaderRoute: typeof AuthenticatedAppFollowupsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/docs': {
      id: '/_authenticated/app/docs'
      path: '/app/docs'
      fullPath: '/app/docs'
      preLoaderRoute: typeof AuthenticatedAppDocsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/crm': {
      id: '/_authenticated/app/crm'
      path: '/app/crm'
      fullPath: '/app/crm'
      preLoaderRoute: typeof AuthenticatedAppCrmRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/buscar': {
      id: '/_authenticated/app/buscar'
      path: '/app/buscar'
      fullPath: '/app/buscar'
      preLoaderRoute: typeof AuthenticatedAppBuscarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/billing': {
      id: '/_authenticated/app/billing'
      path: '/app/billing'
      fullPath: '/app/billing'
      preLoaderRoute: typeof AuthenticatedAppBillingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/agenda': {
      id: '/_authenticated/app/agenda'
      path: '/app/agenda'
      fullPath: '/app/agenda'
      preLoaderRoute: typeof AuthenticatedAppAgendaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/admin': {
      id: '/_authenticated/app/admin'
      path: '/app/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AuthenticatedAppAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/sites/': {
      id: '/_authenticated/app/sites/'
      path: '/app/sites'
      fullPath: '/app/sites/'
      preLoaderRoute: typeof AuthenticatedAppSitesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/sites/$id': {
      id: '/_authenticated/app/sites/$id'
      path: '/app/sites/$id'
      fullPath: '/app/sites/$id'
      preLoaderRoute: typeof AuthenticatedAppSitesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/billing/success': {
      id: '/_authenticated/app/billing/success'
      path: '/success'
      fullPath: '/app/billing/success'
      preLoaderRoute: typeof AuthenticatedAppBillingSuccessRouteImport
      parentRoute: typeof AuthenticatedAppBillingRoute
    }
  }
}

interface AuthenticatedAppBillingRouteChildren {
  AuthenticatedAppBillingSuccessRoute: typeof AuthenticatedAppBillingSuccessRoute
}

const AuthenticatedAppBillingRouteChildren: AuthenticatedAppBillingRouteChildren =
  {
    AuthenticatedAppBillingSuccessRoute: AuthenticatedAppBillingSuccessRoute,
  }

const AuthenticatedAppBillingRouteWithChildren =
  AuthenticatedAppBillingRoute._addFileChildren(
    AuthenticatedAppBillingRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppAdminRoute: typeof AuthenticatedAppAdminRoute
  AuthenticatedAppAgendaRoute: typeof AuthenticatedAppAgendaRoute
  AuthenticatedAppBillingRoute: typeof AuthenticatedAppBillingRouteWithChildren
  AuthenticatedAppBuscarRoute: typeof AuthenticatedAppBuscarRoute
  AuthenticatedAppCrmRoute: typeof AuthenticatedAppCrmRoute
  AuthenticatedAppDocsRoute: typeof AuthenticatedAppDocsRoute
  AuthenticatedAppFollowupsRoute: typeof AuthenticatedAppFollowupsRoute
  AuthenticatedAppLeadsRoute: typeof AuthenticatedAppLeadsRoute
  AuthenticatedAppNewRoute: typeof AuthenticatedAppNewRoute
  AuthenticatedAppReferralsRoute: typeof AuthenticatedAppReferralsRoute
  AuthenticatedAppSettingsRoute: typeof AuthenticatedAppSettingsRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppSitesIdRoute: typeof AuthenticatedAppSitesIdRoute
  AuthenticatedAppSitesIndexRoute: typeof AuthenticatedAppSitesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppAdminRoute: AuthenticatedAppAdminRoute,
  AuthenticatedAppAgendaRoute: AuthenticatedAppAgendaRoute,
  AuthenticatedAppBillingRoute: AuthenticatedAppBillingRouteWithChildren,
  AuthenticatedAppBuscarRoute: AuthenticatedAppBuscarRoute,
  AuthenticatedAppCrmRoute: AuthenticatedAppCrmRoute,
  AuthenticatedAppDocsRoute: AuthenticatedAppDocsRoute,
  AuthenticatedAppFollowupsRoute: AuthenticatedAppFollowupsRoute,
  AuthenticatedAppLeadsRoute: AuthenticatedAppLeadsRoute,
  AuthenticatedAppNewRoute: AuthenticatedAppNewRoute,
  AuthenticatedAppReferralsRoute: AuthenticatedAppReferralsRoute,
  AuthenticatedAppSettingsRoute: AuthenticatedAppSettingsRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppSitesIdRoute: AuthenticatedAppSitesIdRoute,
  AuthenticatedAppSitesIndexRoute: AuthenticatedAppSitesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  SSlugRoute: SSlugRoute,
  ApiPublicMpWebhookRoute: ApiPublicMpWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
