/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SSlugRouteImport } from './routes/s.$slug'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedAppNewRouteImport } from './routes/_authenticated/app.new'
import { Route as AuthenticatedAppLeadsRouteImport } from './routes/_authenticated/app.leads'
import { Route as AuthenticatedAppCrmRouteImport } from './routes/_authenticated/app.crm'
import { Route as AuthenticatedAppBillingRouteImport } from './routes/_authenticated/app.billing'
import { Route as AuthenticatedAppAgendaRouteImport } from './routes/_authenticated/app.agenda'
import { Route as AuthenticatedAppSitesIndexRouteImport } from './routes/_authenticated/app.sites.index'
import { Route as AuthenticatedAppSitesIdRouteImport } from './routes/_authenticated/app.sites.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SSlugRoute = SSlugRouteImport.update({
  id: '/s/$slug',
  path: '/s/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppNewRoute = AuthenticatedAppNewRouteImport.update({
  id: '/app/new',
  path: '/app/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppLeadsRoute = AuthenticatedAppLeadsRouteImport.update({
  id: '/app/leads',
  path: '/app/leads',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppCrmRoute = AuthenticatedAppCrmRouteImport.update({
  id: '/app/crm',
  path: '/app/crm',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppBillingRoute = AuthenticatedAppBillingRouteImport.update({
  id: '/app/billing',
  path: '/app/billing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppAgendaRoute = AuthenticatedAppAgendaRouteImport.update({
  id: '/app/agenda',
  path: '/app/agenda',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppSitesIndexRoute =
  AuthenticatedAppSitesIndexRouteImport.update({
    id: '/app/sites/',
    path: '/app/sites/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppSitesIdRoute = AuthenticatedAppSitesIdRouteImport.update({
  id: '/app/sites/$id',
  path: '/app/sites/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/s/$slug': typeof SSlugRoute
  '/app/agenda': typeof AuthenticatedAppAgendaRoute
  '/app/billing': typeof AuthenticatedAppBillingRoute
  '/app/crm': typeof AuthenticatedAppCrmRoute
  '/app/leads': typeof AuthenticatedAppLeadsRoute
  '/app/new': typeof AuthenticatedAppNewRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/sites/$id': typeof AuthenticatedAppSitesIdRoute
  '/app/sites/': typeof AuthenticatedAppSitesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/s/$slug': typeof SSlugRoute
  '/app/agenda': typeof AuthenticatedAppAgendaRoute
  '/app/billing': typeof AuthenticatedAppBillingRoute
  '/app/crm': typeof AuthenticatedAppCrmRoute
  '/app/leads': typeof AuthenticatedAppLeadsRoute
  '/app/new': typeof AuthenticatedAppNewRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/sites/$id': typeof AuthenticatedAppSitesIdRoute
  '/app/sites': typeof AuthenticatedAppSitesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/s/$slug': typeof SSlugRoute
  '/_authenticated/app/agenda': typeof AuthenticatedAppAgendaRoute
  '/_authenticated/app/billing': typeof AuthenticatedAppBillingRoute
  '/_authenticated/app/crm': typeof AuthenticatedAppCrmRoute
  '/_authenticated/app/leads': typeof AuthenticatedAppLeadsRoute
  '/_authenticated/app/new': typeof AuthenticatedAppNewRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/sites/$id': typeof AuthenticatedAppSitesIdRoute
  '/_authenticated/app/sites/': typeof AuthenticatedAppSitesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/s/$slug'
    | '/app/agenda'
    | '/app/billing'
    | '/app/crm'
    | '/app/leads'
    | '/app/new'
    | '/app/'
    | '/app/sites/$id'
    | '/app/sites/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/s/$slug'
    | '/app/agenda'
    | '/app/billing'
    | '/app/crm'
    | '/app/leads'
    | '/app/new'
    | '/app'
    | '/app/sites/$id'
    | '/app/sites'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/s/$slug'
    | '/_authenticated/app/agenda'
    | '/_authenticated/app/billing'
    | '/_authenticated/app/crm'
    | '/_authenticated/app/leads'
    | '/_authenticated/app/new'
    | '/_authenticated/app/'
    | '/_authenticated/app/sites/$id'
    | '/_authenticated/app/sites/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  SSlugRoute: typeof SSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$slug': {
      id: '/s/$slug'
      path: '/s/$slug'
      fullPath: '/s/$slug'
      preLoaderRoute: typeof SSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/new': {
      id: '/_authenticated/app/new'
      path: '/app/new'
      fullPath: '/app/new'
      preLoaderRoute: typeof AuthenticatedAppNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/leads': {
      id: '/_authenticated/app/leads'
      path: '/app/leads'
      fullPath: '/app/leads'
      preLoaderRoute: typeof AuthenticatedAppLeadsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/crm': {
      id: '/_authenticated/app/crm'
      path: '/app/crm'
      fullPath: '/app/crm'
      preLoaderRoute: typeof AuthenticatedAppCrmRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/billing': {
      id: '/_authenticated/app/billing'
      path: '/app/billing'
      fullPath: '/app/billing'
      preLoaderRoute: typeof AuthenticatedAppBillingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/agenda': {
      id: '/_authenticated/app/agenda'
      path: '/app/agenda'
      fullPath: '/app/agenda'
      preLoaderRoute: typeof AuthenticatedAppAgendaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/sites/': {
      id: '/_authenticated/app/sites/'
      path: '/app/sites'
      fullPath: '/app/sites/'
      preLoaderRoute: typeof AuthenticatedAppSitesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/sites/$id': {
      id: '/_authenticated/app/sites/$id'
      path: '/app/sites/$id'
      fullPath: '/app/sites/$id'
      preLoaderRoute: typeof AuthenticatedAppSitesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppAgendaRoute: typeof AuthenticatedAppAgendaRoute
  AuthenticatedAppBillingRoute: typeof AuthenticatedAppBillingRoute
  AuthenticatedAppCrmRoute: typeof AuthenticatedAppCrmRoute
  AuthenticatedAppLeadsRoute: typeof AuthenticatedAppLeadsRoute
  AuthenticatedAppNewRoute: typeof AuthenticatedAppNewRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppSitesIdRoute: typeof AuthenticatedAppSitesIdRoute
  AuthenticatedAppSitesIndexRoute: typeof AuthenticatedAppSitesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppAgendaRoute: AuthenticatedAppAgendaRoute,
  AuthenticatedAppBillingRoute: AuthenticatedAppBillingRoute,
  AuthenticatedAppCrmRoute: AuthenticatedAppCrmRoute,
  AuthenticatedAppLeadsRoute: AuthenticatedAppLeadsRoute,
  AuthenticatedAppNewRoute: AuthenticatedAppNewRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppSitesIdRoute: AuthenticatedAppSitesIdRoute,
  AuthenticatedAppSitesIndexRoute: AuthenticatedAppSitesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  SSlugRoute: SSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
